### ISSUE TITLE
Which Arduino Board?

### ISSUE THREAD

**Issue by dakota72** [RealCorebb/ESP32-A1s-Audio-Kit#1]
Hi,
My best compliments for your job.
I cannot compile with Arduino IDE, because I don't know which board I must use.
I installed Esp32 Boards and ESP8266 Boards, but it does not appear in either of them.
thanks,
dak

**Comment by RealCorebb** [comment]
It should be ESP32 Dev Board, and enable the PSRAM
You should go https://github.com/espressif/arduino-esp32 for how to install the ESP32 boards in Arduino IDE
